services:
  # NestJS 应用服务
  api:
    image: ${DOCKERHUB_USERNAME}/nest-app:latest
    container_name: nest_api
    ports:
      - "3000:3000"
    env_file:
      - .dev.env
    depends_on:
      - mysql
    networks:
      - backend

  # MySQL 服务配置
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  # Adminer 服务配置
  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mysql

# 持久化存储
volumes:
  mysql_data:
    driver: local

# 网络配置
networks:
  backend:
    driver: bridge