name: Deploy to Aliyun

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      # 安装依赖并构建
      - name: Install and Build
        run: |
          yarn install
          yarn build
          ls

      # 部署到服务器
      - name: Deploy to Aliyun ECS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH }}
          script: |
            rm -rf /home/${{ secrets.ALIYUN_USERNAME }}/nest-app
            mkdir -p /home/${{ secrets.ALIYUN_USERNAME }}/nest-app

      # 将构建产物传输到服务器
      - name: Copy build artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH }}
          source: 'dist/,docker-compose.yml,.env,package.json,yarn.lock'
          target: '/home/${{ secrets.ALIYUN_USERNAME }}/nest-app'

      # 重启数据库服务
      - name: Restart Database Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH }}
          script: |
            cd /home/${{ secrets.ALIYUN_USERNAME }}/nest-app
            docker compose down || true
            docker rm -f my_mysql my_adminer || true
            docker compose up -d
