name: Deploy to Aliyun

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH }}
        script: |
          cd /home/${{ secrets.ALIYUN_USERNAME }}/nest-app
          git pull origin deploy
          docker compose down
          docker compose up -d --build 