name: Deploy to Aliyun

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH }}
        script: |
          # 先配置 git 跳过 host key 检查
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
          cd /home/${{ secrets.ALIYUN_USERNAME }}/nest-app
          git clone git@github.com:WhiteP1ay/nest-learn.git
          cd nest-learn
          docker compose down
          docker compose up -d --build