name: Deploy to Aliyun

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'
    
    # 安装依赖并构建
    - name: Install and Build
      run: |
        yarn install
        yarn build
    
    # 登录到 Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 构建并推送 Docker 镜像
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_ACCOUNT }}/nest-app:latest
    
    # 部署到服务器
    - name: Deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH }}
        script: |
          cd /home/${{ secrets.ALIYUN_USERNAME }}/nest-app
          docker compose pull
          docker compose down
          docker compose up -d